version: '3'

services:
  postgresql:
    build: ./
    image: postgresql:14
    container_name: db
    ports:
      - 5433:5432
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  flyway-manual-docs:
    image: flyway/flyway:latest
    container_name: flyway_manual_docs
    command: -connectRetries=60
      -configFiles=/flyway/conf/flyway.conf
      migrate

    volumes:
      - ./rgo-cloud-db-docs-migration/src/main/resources/db/manual:/flyway/sql
      - ./rgo-cloud-db-docs-migration/src/main/resources/flyway/config/manual:/flyway/conf
    depends_on:
      postgresql:
        condition: service_healthy


  flyway-migration-docs:
    image: flyway/flyway:latest
    container_name: flyway_migration_docs
    command: -connectRetries=60
      -configFiles=/flyway/conf/flyway.conf
       migrate

    volumes:
      - ./rgo-cloud-db-docs-migration/src/main/resources/db/migration:/flyway/sql
      - ./rgo-cloud-db-docs-migration/src/main/resources/flyway/config/migration:/flyway/conf
    depends_on:
      - flyway-manual-docs
    restart: on-failure


  flyway-manual-auth:
    image: flyway/flyway:latest
    container_name: flyway_manual_auth
    command: -connectRetries=60
      -configFiles=/flyway/conf/flyway.conf
      migrate

    volumes:
    - ./rgo-cloud-db-auth-migration/src/main/resources/db/manual:/flyway/sql
    - ./rgo-cloud-db-auth-migration/src/main/resources/flyway/config/manual:/flyway/conf
    depends_on:
      postgresql:
        condition: service_healthy


  flyway-migration-auth:
    image: flyway/flyway:latest
    container_name: flyway_migration_auth
    command: -connectRetries=60
      -configFiles=/flyway/conf/flyway.conf
      migrate

    volumes:
      - ./rgo-cloud-db-auth-migration/src/main/resources/db/migration:/flyway/sql
      - ./rgo-cloud-db-auth-migration/src/main/resources/flyway/config/migration:/flyway/conf
    depends_on:
      - flyway-manual-auth
    restart: on-failure